### PR TITLE
Android 12 accuracy issue

### LINKED ISSUE #59: Android 12 issues
**Describe the bug**
Location is not working well for android 12.
I'm still not sure what and why and this requires more investigation.
The only lead I have is this article:
https://developer.android.com/training/location/permissions#approximate-request

**To Reproduce**
Not sure...

**Expected behavior**
GPS should work

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] android 12

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] pixel 4a

### PR DESCRIPTION
**Pull request by HarelM**
Fixes #59

### CODE REVIEW

**Comment by HarelM** [comment]
@raddishiow let me know if you would like to review this.
Otherwise I'll merge and publish a new version.

**Comment by RaddishIoW** [comment]
If you're happy I am - only had a cursory look through but seems good.
Nice one.

**Comment by HarelM** [comment]
@RaddishIoW can we migrate out of the dev and main branch thing?
Last publishes I did were not successful or had issues due to this approach...

**Comment by RaddishIoW** [comment]
Yep - it's getting in the way and doesn't actually solve anything.
I think we'd just need to remove the GitHub actions relating to it? Then we can just merge the dev into main and be done with it?

**Comment by HarelM** [comment]
Ok, I'll work on it before the release.

**Pull request merged**
