### PR TITLE
Adds promises and subscription

### LINKED ISSUE #16: Add promises and subscription to js interface
I'm not sure how this is done, but most of the plugins has a nice Ionic Native wrapper which helps using them and works in promises and modern stuff.
I would like this plugin to enjoy this support, I'm not familiar with the Ionic Native process in order to make this work, I guess we'll need to learn...
Adding this as a place holder for future improvements.

### PR DESCRIPTION
**Pull request by HarelM**
Resolves #16

### CODE REVIEW

**Comment by HarelM** [comment]
@RaddishIoW let me know if you want to review this.

**Review by RaddishIoW — APPROVED** [review]
Looks great! Nice work 👍🏼

**Comment by RaddishIoW** [comment]
Could do with updating the docs to reflect these changes before releasing 1.1, so the docs are consistent with the plugin.

**Comment by HarelM** [comment]
I'll see what I can do, great job on the docs by the way!!

**Pull request merged**
