### PR TITLE
Potential fix for #19

### PR DESCRIPTION
**Pull request by RaddishIoW**

### CODE REVIEW

**Comment by HarelM** [comment]
I've study this to some extent.
Please note that this permission will require you to explain why you need to use geolocation in the background without telling the user so.
I tried to explain in the store why I need this permission and didn't get a respond or an approval.
When you use geolocation in the background but you have a notification icon to show that your app is running you don't need this permission and it is not considered background.
I'll link to the original issue in the repo where I found a video about it.

**Comment by HarelM** [comment]
See my comment here:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/688#issuecomment-719002549

**Comment by HarelM** [comment]
I think this PR can be canceled...?

**Comment by RaddishIoW** [comment]
Yeah you're probably right - I think it would be needed for the "Headless Mode" on android... but I think we should probably do away with that in 2.0?
Might be worth noting in the docs why we don't need this permission and why it's not included?

**Comment by HarelM** [comment]
Sure. I'm not sure how interesting headless mode is for app developers... Getting the permission in the play store is hard and seems like a barrier. at least for me it was...
In any case, adding some information in the documentation is a good idea.

**Pull request closed without merging**
