### PR TITLE
GPS transactional location fetch

### LINKED ISSUE #18: [Feature] Transaction-based access to the GPS positions buffer
See here: https://github.com/IsraelHikingMap/Site/issues/1427

When using the locations buffer to get the location from the plugin and after that deleting the location buffer it might get to a race condition where the delete happens after a location was added or that getting all location will happen before all locations were deleted.

## Your Environment
* Plugin version: 1.0
* Platform: Android (observed there but might be on iOS too)
* OS version: 9
* Device manufacturer and model: An old tablet
* Cordova version (`cordova -v`): 10.0
* Cordova platform version (`cordova platform ls`): Android 9.1
* Plugin configuration options: Not so relevant
* Link to your project: See issue above for a link to the project

## Context
Problem in getting GPS positions while the app is going back and forth from the background 

## Expected Behavior
Allow the app not to miss or duplicate positions

## Actual Behavior
Positions are duplicated or missed

## Possible Fix
Add an API method to do both get and delete

## Steps to Reproduce
1. Hard to say, but using the get locations and then right after the delete locations
2.
3.
4.

## Context
See screen shot in linked issue

## Debug logs
Not available

### PR DESCRIPTION
**Pull request by HarelM**
Resolves #18

### CODE REVIEW

**Comment by HarelM** [comment]
@raddishiow can you please reviews this so I can merge and release?
Sorry for nagging...

**Comment by RaddishIoW** [comment]
Yeah of course, sorry - I'll take a look ASAP.

**Review by RaddishIoW — APPROVED** [review]
All looks good to me.

**Comment by RaddishIoW** [comment]
@HarelM When you're ready, I think we're all good to merge and make a 1.1.0 release?

**Pull request merged**
