### PR TITLE
Workflow to merge to stable branch on release

### PR DESCRIPTION
**Pull request by RaddishIoW**
New workflow that automatically merges the changes from develop to stable on creation of a release.

### CODE REVIEW

**Comment by HarelM** [comment]
Wouldn't this implementation create a race condition between the two flows?
1st one will start creating an npm package while the second one merges the branches?
I can have a go at it right now, but I'm not sure it is worth trying it out if I think there's a problem in current implementation, isn't it?

**Comment by HarelM** [comment]
I created a tag to see if it will work or not... it didn't... :-( ​
The branch used for npm publish is the default, which is now still in version 1.0.0, so publish to npm fails...
Also the flow that merges the branches still doesn't run as it is on the develop branch which is now not the default.
An option to solve this is release the npm package from the develop branch so that the merge will not affect the process.
In any case, let me know how you want to solve this...

**Comment by HarelM** [comment]
@RaddishIoW I've manually merged develop branch which seems to accidentally delete it...
I've published version 1.1.0 by creating a release and I think the npm package is as expected.
I guess this process need a rethink... Let me know if you would like my help on this...

**Comment by RaddishIoW** [comment]
Hmmm... OK well that didn't work then! :)
I'll take a look at this today. TBH, I expected there to be some issues.
The fact that the `develop` branch was deleted was probably because you used a PR to merge into `stable`, rather than just merging. IIRC the settings are to delete the branch that is merged when you merge a PR.

I've recreated the `develop` branch from the stable branch, and set GitHub Pages to use the `stable` branch.

**Comment by HarelM** [comment]
Where are we with this? Did you get the time to fix it.
Maybe you can simply add a `needs` to the job so that the merge will happen before the npm publishing.
I'm asking as I don't remember how to publish a version.
We should probably add some documentation on it so we won't forget...?

**Comment by RaddishIoW** [comment]
Hmm... documenting it is probably a good idea! :)
I'll be working on this plugin in the next couple of days, so I'll come back to this and try and sort something out.

**Comment by HarelM** [comment]
It's currently a bit broken, I tried some stuff that didn't work with the "needs". Feel free to fix and document...

**Pull request merged**
