### PR TITLE
fixed notification handler override

### PR DESCRIPTION
**Pull request by RaddishIoW**
fix for issues #627 and #682

### CODE REVIEW

**Review by HarelM — APPROVED** [review]
I'm not familiar with this code, but the fix looks fine.

**Comment by RaddishIoW** [comment]
I'm not familiar either, and I'm not sure if it's still an issue... I'll have to investigate further before we can merge or not.

**Comment by HarelM** [comment]
@RaddishIoW can this be closed? merge? how do you want to play it?

**Comment by RaddishIoW** [comment]
I can't say that I've seen the issue that this resolves myself, so it's difficult to say.
This was a PR that was brought in from someone else's fork of the mauron85 repo.

I guess we can close this now, and if someone does run into an issue with the notifications then we've got a potential fix ready to go.

**Pull request closed without merging**
