### PR TITLE
Update android-permissions plugin

### PR DESCRIPTION
**Pull request by jwasnoggin**
Updated android-permissions plugin as discussed in #169

### CODE REVIEW

**Comment by HarelM** [comment]
THANKS!
I assume you have tested this, right?
Can you update the package version as well so that I'll be able to easily release this?

**Comment by jwasnoggin** [comment]
I have tested it although not exhaustively. From what I've seen it works fine. 
Version number updated.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
THANKS!

**Comment by HarelM** [comment]
I've just released a new version, let me know if you have any issues using it.

**Pull request merged**
